### PR TITLE
[no-Jira] Move InfiniteList components outside of ContactRow

### PR DESCRIPTION
**Pull request by canac**
## Description

The goal is to optimize the rendering of InfiniteList. One issue was that the contacts list was defining its components inside of another component, causing them to be unmounted and remounted on every render.

It's a little hard to tell in the screen capture, but it appears that there is more whitespace at the bottom when scrolling in the old version.

https://github.com/CruGlobal/mpdx-react/assets/3740187/13d9ae33-4679-42e7-98bd-b817415fd8f5

https://github.com/CruGlobal/mpdx-react/assets/3740187/06ba455d-b85b-45b7-8f60-85dd4bdccfa1

The `InfiniteList` `EmptyPlaceholder` should also be a stable component function, but I ran out of time to fix that.

@caleballdrin Do you want to test this out and see if it helps improve things?

## Checklist:

- [x] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [x] I have requested a review from another person on the project

### CODE REVIEW

**Comment by canac** [comment]
Also, the `scrollSeekConfiguration` option is what makes the list hide when you scroll fast ([docs](https://virtuoso.dev/scroll-seek-placeholders/)). The idea is to save cycles rendering, but it arguably degrades the UX and makes the list seem jankier because it waits for user to stop scrolling to show the items again. We can consider removing that option.

**Comment by wrandall22** [comment]
Since this seems to be focused on improving performance, can we make sure to run LighthouseCI with this PR?

**Comment by canac** [comment]
run lighthouse

**Comment by canac** [comment]
run lighthouse

**Comment by canac** [comment]
@wrandall22 Good idea! There's some issues with the preview environments being spun up because of code in MPDX API staging. `yarn gql` always fails with `Value "PRAYER_REQUEST" does not exist in "ActivityTypeEnum" enum at mpdx-react/src/components/Dashboard/ThisWeek/GetThisWeek.graphql:43:34`. (I think it got renamed to `PARTNER_CARE_PRAYER_REQUEST`).

It may or may not be related, but I'm also seeing errors in the CI workflow https://github.com/CruGlobal/mpdx-react/actions/runs/9084046556/job/24964220126.

**Comment by wrandall22** [comment]
Hmm, `ERR_CONNECTION_REFUSED at http://localhost:3000` it is not hitting the right url, maybe due to the failed preview environment...

**Review by caleballdrin — APPROVED** [review]
Looks great! I'll play around with the settings and talk to Scott about UX vs speed.

**Comment by canac** [comment]
@dr-bizz I'd love to get your eyes on this too before it merges. If it looks good, feel free to merge it at your convenience.

**Pull request merged**
