### PR TITLE
HelpScout - 1154070 - Limit contact merge

### PR DESCRIPTION
**Pull request by dr-bizz**
## Description
Limiting the number of contacts a user can merge together prevents an [issue like this](https://secure.helpscout.net/conversation/2594181084/1154070/) from happening again.

I've added a limit of eight contacts. I've also added tests to ensure the functionality works.

## Checklist:

- [ ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

### CODE REVIEW

**Comment by caleballdrin** [comment]
It looks like the amplify preview is not working for some reason.

**Comment by dr-bizz** [comment]
The PR Preview doesn't work due to the issue on staging with constants

**Comment by dr-bizz** [comment]
@caleballdrin Can you review without the PR or pull it down locally?

**Review by caleballdrin — APPROVED** [review]
I tested this locally and it stopped me from trying to merge more than 8 contacts. Looks great!

**Pull request merged**
