### PR TITLE
Update GraphQL Usage

### PR DESCRIPTION
**Pull request by reldredge71**
Two fixes:
- convert the `referrer` input on the `contacts` endpoint from an enum to an array of strings
- remove `appeals` from the Rest-to-GraphQL implementation, since it seems to have been implemented on Rails now.

### CODE REVIEW

**Comment by reldredge71** [comment]
I think these tests are failing because the 'referrer' changes in https://github.com/CruGlobal/mpdx_api/pull/2404 have not been merged to production yet?

**Review by OzzieOrca — APPROVED** [review]

**Comment by reldredge71** [comment]
@OzzieOrca what should we do about the failing tests?  I think @soberstadt 's PR needs to be put to prod for these errors to go away... I'm testing it on stage now but overall it looks good

**Review by CSimbulan — APPROVED** [review]

**Review by hotcakedev628 — APPROVED** [review]

**Comment by OzzieOrca** [comment]
I guess let's just force merge it to keep development going. main won't deploy until Spencer's work makes it to production. Although every PR to main after is going to have status checks fail... Hmm.

**Comment by reldredge71** [comment]
I'll force merge it since it's holding many of us up.

**Pull request merged**
