### PR TITLE
[MPDX-8221] Align 14 month reports with Angular

### PR DESCRIPTION
**Pull request by canac**
## Description

One major discrepancy I saw is that the 14 month reports were actually including 15 months. I adjusted the date range in the query to match Angular.

@wrandall22 Do you want to test again in preview that this fixes the discrepancies you were seeing? The numbers match on my account now, besides rounding differences (React is more accurate).

[MPDX-8221](https://jira.cru.org/browse/MPDX-8221) and [MPDX-8228](https://jira.cru.org/browse/MPDX-8228)

## Checklist:

- [x] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [x] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [x] I have requested a review from another person on the project

### CODE REVIEW

**Review by dr-bizz — COMMENTED** [review]
The code looks good. I'll let Bill review the UI and check the details match.

**Comment by canac** [comment]
@wrandall22 Which environment is that first screenshot from (local, staging, preview, prod)? I'm seeing different numbers in the report in local and preview. Also, which account list id are you using? Thanks.

**Comment by wrandall22** [comment]
Both screenshots are from the preview environment with the Pedro Perez account list

**Comment by canac** [comment]
@wrandall22 I think that some of the problems stem from the fact that the React 14 month reports only show one table instead of one table per currency. I'm working on a fix for that as part of https://jira.cru.org/browse/MPDX-8227. I also fixed the column alignment issue you pointed out. If the code in this PR looks good, I'll merge it but keep the Jira ticket open until we can verify that the upcoming fixes for MPDX-8227 fix the remaining inconsistencies you're seeing.

**Comment by wrandall22** [comment]
Alignment looks good.

**Review by wrandall22 — APPROVED** [review]

**Pull request merged**
