### PR TITLE
[No-Jira] Change tools links

### PR DESCRIPTION
**Pull request by caleballdrin**
## Description

Change url of tools pages to the same as angular.

## Checklist:

- [ ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

### CODE REVIEW

**Comment by caleballdrin** [comment]
@dr-bizz I'm not sure why codecov failed. I haven't changed any logic.

**Comment by dr-bizz** [comment]
It is because you've moved the pages around. You will need to create a test for `/fix/commitmentInfo` and `/fix/phoneNumbers`, which will help boost your score, but probably not by 30%.

Maybe try that and then if that doesn't boost the score, we'll go from there.

**Review by dr-bizz — CHANGES_REQUESTED** [review]
It all looks good, just need CodeCov to pass.

**Comment by caleballdrin** [comment]
@dr-bizz can you approve this? There is a PR's already for Fix Commitment info that has the test but it hasn't been merged in yet. I don't think this PR should add tests for functionality that wasn't changed in this PR.

**Review by dr-bizz — APPROVED** [review]
Great work on this

**Pull request merged**
